version: "3.1"

services:
    postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_DB: togo-db
        ports:
            - 5432:5432
        volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - local
    api:
        image: togo-api
        build:
            context: ./
        ports:
            - 5050:5050
        environment:
            DB_HOST: postgres
            DB_PORT: 5432
            DB_USER: postgres
            DB_PASSWORD: mysecretpassword
            DB_NAME: togo-db
        networks:
            - local
networks:
    local: